version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: water-harvest-notifier
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
